# This is a sample build configuration for Maven.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.3.3

pipelines:
  branches:
    master:
      - step:
          script:
            - mvn clean install -V -B -s settings.xml deploy
    develop:
      - step:
          script:
          - mvn clean install -V -B -s settings.xml deploy
    feature/*:
      - step:
          caches:
          - maven
          script:
          - mvn clean install