service:
  confirm:
    timeout: 30
  pageablelist:
    timeout: 180
    next_amount: 10
  localization:
    locale_dir: "locale"
    locale: "de_DE"
    file_name: "permissions.yml"
    no_role: "no_role"
    role_key: "permission_roles_enabled"
metrics:
  use: false