# Each section and option in this file can be overridden by a plugin configuration that depends on the BedrockPlugin

# Section for service configuration
service:
  # Color Scheme Service
  colorscheme:
    # The name of the scheme to be used.
    # Currently there are these schemes available:
    #   DEFAULT, RED, GREEN, BLUE, YELLOW and CUSTOM
    name: "DEFAULT"
    # If you want to use a custom color scheme, you can specify colors like so:
    #
    #  name: "CUSTOM"
    #  primary: "GOLD"
    #  secondary: "YELLOW"
    #  flag: "DARK_GRAY"
    #  text: "WHITE"

  # Confirm Service
  confirm:
    # The timeout value. After this a confirm command is being invalidated
    timeout: 30

  # Pageable List Service
  pageablelist:
    # After this timeout a pageable list is being invalidated
    timeout: 180
    # Amount of entries per page
    next_amount: 10

  # Localization service
  localization:
    # path to directory where locales reside
    locale_dir: "locale"
    # the default locale that is being represented by a file, e.g. "de_DE.yml"
    locale: "de_DE"

  # Permission service
  permission:
    # File where all permissions are stored and read from
    file_name: "permissions.yml"
    # Does Operators have all permissions? Valid values are true or false
    grant_all_permissions_to_op: true
    # custom permission prefix. If left empty or undefined the lowercased plugin name will be taken as prefix
    prefix: "bedrock"

# mcstats.org metrics
metrics:
  # Use plugin metrics on mcstats.org, defaults to false
  use: false

# Configuration version - do not touch (for later usage in PluginConfigurationService)
version: "0.8.9~spigot187+1"