author: Cube-Nation, B1acksheep, d1rty
description: Comprehensive Plugin API
main: de.cubenation.plugin.bedrock.BedrockPlugin
database: true
load: startup
name: Bedrock
version: "${project.version}"
api-version: 1.15

depend:
  - Yamler

commands:
  bedrockplayer:
    description: Bedrock Player Debug Command
    aliases: bp
  ${project.artifactId}:
    description: Bedrock Base Command