author: Cube-Nation, B1acksheep, d1rty
description: Cube-Nation Plugin Base
main: de.cubenation.bedrock.BedrockPlugin
database: true
load: startup
name: Bedrock
version: "${project.version}"
depend:
  - Yamler
commands:
  bedrockplayer:
    description: Bedrock Player Command
    aliases: bp
  ${project.artifactId}:
    description: Bedrock Base Command